---
# handlers file for ansible-role-sonarqube/
- name: "Restart SonarQube service"
  ansible.builtin.service:
    name: sonar
    state: restarted

- name: "Fail if expected sonar version not confirmed"
  ansible.builtin.fail:
    msg: Please check if 'Version' field of http://{{ inventory_hostname }}{{ sonar_web_context }} match to {{ sonar_version }}

- name: "Warn about post-upgrade steps"
  ansible.builtin.debug:
    msg:
      - "SonarQube version changed to {{ sonar_version }} but additional actions required from your side"
      - "Visit http://{{ inventory_hostname }}{{ sonar_web_context }}/setup to follow the post-upgrade procedure"
