---
- name: Converge
  hosts: all
  vars:
    sonar_version: 7.9.6
    sonar_web_host: 127.0.0.1
    sonar_plugins:
      - name: "sonar-l10n-pt"
        version: "6.4"
        commercial: false
        url: "https://github.com/felipebz/sonar-l10n-pt/releases/download/v6.4/sonar-l10n-pt-plugin-6.4.jar"
      - name: "sonar-html-plugin"
        version: "3.2.0.2082"
        commercial: false
      - name: "ansible"
        version: "2.5.1"
        marketplace: true
      - name: "ha"
        version: "7.1"
        marketplace: true
      - name: "ha"
        version: "7.1"
        marketplace: true
      - name: "authgithub"
        version: "1.5"
        marketplace: true
      - name: "authgitlab"
        version: "1.3.2"
        marketplace: true
      - name: "authgoogleoauth"
        version: "1.6.1"
        marketplace: true
  # pre_tasks:
  #   # TODO: Prepare Java 11
  #   - name: install openjdk (redhat)
  #     ansible.builtin.package:
  #       name: java-11-openjdk
  #       state: present
  #     when: ansible_facts['os_family'] == "RedHat"
  #   - name: add backports repository
  #     ansible.builtin.apt_repository:
  #       repo: deb http://ftp.debian.org/debian stretch-backports main
  #       state: present
  #       update_cache: yes
  #     when: ansible_facts['os_family'] == "Debian"
  #   - name: install openjdk (debian)
  #     ansible.builtin.apt:
  #       name: openjdk-11-jdk
  #       state: present
  #     when: ansible_facts['os_family'] == "Debian"
  roles:
    - role: ansible-role-sonarqube
