---
- name: Prepare
  hosts: all

  roles:
    - name: buluma.bootstrap
    - name: buluma.epel
    # - name: buluma.java

  tasks:
    - name: "ensure apt cache is up to date"
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: "install package dependencies"
      ansible.builtin.package:
        name: "{{ item }}"
        state: "present"
      with_items:
        - unzip
